name: 'O&W Adventures'
favicon: null
layout_spectrum: 0.26271
typography_spectrum: 0.49067
title: 'O&W in Los Angeles'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7d5939'
    - '#171812'
    - '#b6b6b8'
    - '#ba7b5c'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
