name: 'O&W Adventures'
favicon: null
layout_spectrum: 0.84941
typography_spectrum: 0.5146
title: 'O&W in Los Angeles'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6c7aa'
    - '#527dc1'
    - '#fffffa'
    - '#262d37'
    - '#be2134'
  brandStrength: 0.125
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
