name: 'O&W Adventures'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5146
title: 'O&W in Los Angeles'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#11110f'
    - '#305eb6'
    - '#b17b4f'
    - '#96c9f8'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
